baseURL = "https://hyun-s.github.io/"
languageCode = "en-us"
title = "Hyunsoo Han - Personal Website"

[params]
    author = "Hyunsoo Han"
    description = "Personal website for Hyunsoo Han, researcher in AI Diffusion Model Compression"

[outputs]
  home = ["html", "rss"]
  section = ["html"]
  page = ["html"]
  taxonomy = ["html"]

[build]
  buildStats = false
  ignoreCache = true
  disableKinds = ["rss"]

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  section = "/:slug/"